--[[ C5Hub: Universal ]]--
local MSG = game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest
MSG:FireServer("Loading C5Hub Universal.." ,"All")
wait(2)
MSG:FireServer("Version of C5Hub is V1" ,"All")
loadstring(game:HttpGet("https://pastebin.com/raw/r97d7dS0", true))()
wait(0.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/fatesc/fates-admin/main/main.lua"))();
wait(0.2)
loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/PolarWasHere/Arctic/main/Arctic"))()
wait(0.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()
wait(0.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source", true))()
wait(0.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/topitbopit/rblx/main/jeff_gui.lua", true))()
wait(0.2)
loadstring(game:HttpGet("https://raw.githubusercontent.com/topitbopit/jeffs-speed-gui/main/gui.lua", true))()
wait(0.2)
loadstring(game:HttpGet("https://pastebin.com/raw/iL4NRDux", true))()
wait(0.2)
loadstring(game:HttpGet("https://pastebin.com/raw/Np5XYrts", true))()
wait(2)
MSG:FireServer("Loaded C5Hub Universal." ,"All")
